---
#: GitHub actions workflow for building chroot tarballs
#: for ma'shmallow-0 testing environments.

name: build-tarballs

on:
  push:
    branches:
      # any branches; $default-branch doesn't seem to work
      - main
      - 46-tarball-ci-action
      # - '*'
  schedule:
    # every monday, thursday, friday, 3:15am EEST
    - cron:  '15 0 * * 1,3,5'

jobs:
  build-focal-headless:

    runs-on: ubuntu-latest
    environment: STAGE

    env:
      MASH_CHROOT_TAR_EXT: xz
      MASH_CHROOT_USER_PSSWD_HASH: ${{ secrets.MASH_CHROOT_USER_PSSWD_HASH }}
      MASH_CHROOT_RELEASE_TAG: ${{ secrets.MASH_CHROOT_RELEASE_TAG }}

    steps:
      - uses: actions/checkout@v2
        # with:
        #   ref: main
      - run: sudo apt-get update
      - run: sudo apt-get install -y debootstrap make curl
      - run: ./scripts/create-dot-env.sh > .env.mk
      - run: make build/focal-headless.tar.${MASH_CHROOT_TAR_EXT}
      - run: make build/focal-mate-desktop.tar.${MASH_CHROOT_TAR_EXT}
      - run: echo ${{ secrets.YASSENS_GITHUB_TOKEN }} | gh auth login --with-token
      - run: gh release upload --clobber ${MASH_CHROOT_RELEASE_TAG} ./build/focal-headless.tar.${MASH_CHROOT_TAR_EXT}
      - run: gh release upload --clobber ${MASH_CHROOT_RELEASE_TAG} ./build/focal-mate-desktop.tar.${MASH_CHROOT_TAR_EXT}
