---
#: GitHub actions workflow for building chroot tarballs
#: for ma'shmallow-0 testing environments.

name: build-tarballs

on:
  push:
    branches:
      # any branches
      - main
      - '*'
      # - 46-tarball-ci-action
  schedule:
    # every monday and thursday, 2:15 in the morning
    - cron:  '15 2 * * 1,3'

jobs:
  build-focal-headless:

    runs-on: ubuntu-latest

    env:
      MASH_CHROOT_TAR_EXT: gz
      MASH_CHROOT_USER_PSSWD_HASH: $$6$$coq/LvbNylektqbU$$yZ02jL5Q2mSPlL1VnLEb9jnenFqDRbslk9jbRQ.RCRNMtxwCH//NWYK.zowhjFFm6N5RI9WPVI4kWgcX2jDoV/

    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get update
      - run: sudo apt-get install -y debootstrap make curl
      - run: ./scripts/create-dot-env.sh > .env
      - run: make build/focal-headless.tar.${{ env.MASH_CHROOT_TAR_EXT }}
