---
#: GitHub actions workflow for building chroot tarballs
#: for ma'shmallow-0 testing environments.

name: build-tarballs

on:
  push:
    branches:
      # any branches
      - main
      - 46-tarball-ci-action
      # - '*'
  schedule:
    # every monday, thursday, friday, 4:15am EEST
    - cron:  '15 1 * * 1,3,5'

jobs:
  build-focal-headless:

    runs-on: ubuntu-latest

    env:
      MASH_CHROOT_TAR_EXT: ${{ secrets.MASH_CHROOT_TAR_EXT }}
      MASH_CHROOT_USER_PSSWD_HASH: ${{ secrets.MASH_CHROOT_USER_PSSWD_HASH }}
      MASH_CHROOT_RELEASE_TAG: ${{ secrets.MASH_CHROOT_RELEASE_TAG }}

    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get update
      - run: sudo apt-get install -y debootstrap make curl
      - run: ./scripts/create-dot-env.sh > .env
      - run: make build/focal-headless.tar.${{ env.MASH_CHROOT_TAR_EXT }}
      - run: gh release upload --clobber ${{ env.MASH_CHROOT_RELEASE_TAG }} ./build/focal-headless.tar.${{ env.MASH_CHROOT_TAR_EXT }}
      - run: gh release upload --clobber ${{ env.MASH_CHROOT_RELEASE_TAG }} ./build/focal-mate-desktop.tar.${{ env.MASH_CHROOT_TAR_EXT }}
